services:
   openvpn:
     container_name: openvpn
     image: vip8/openvpn:latest
     sysctls:
       - net.ipv6.conf.all.disable_ipv6=0
       - net.ipv6.conf.default.forwarding=1
       - net.ipv6.conf.all.forwarding=1
     environment:
       TZ: Asia/Shanghai
     volumes:
      - "./data:/etc/openvpn"
     ports:
      - '28039:1194/udp'
     cap_add:
      - NET_ADMIN
     restart: always
     privileged: true
